# .github/workflows/tagging.yml
name: Automated Tagging
on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Create Tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          IFS='.' read -r MAJOR MINOR PATCH <<< "${LATEST_TAG#v}"
          NEW_PATCH=$((PATCH + 1))
          NEW_TAG="v${MAJOR}.${MINOR}.${NEW_PATCH}"
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a $NEW_TAG -m "Release ${NEW_TAG}"
          git push origin $NEW_TAG